/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "../ud923-p4l1-square.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
square_proc_1(square_in *argp, square_out *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, SQUARE_PROC,
		(xdrproc_t) xdr_square_in, (caddr_t) argp,
		(xdrproc_t) xdr_square_out, (caddr_t) clnt_res,
		TIMEOUT));
}
